# -*- coding: utf-8 -*-
"""extraction-transformation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4eAV7vHjJNbQrRKv41oDyIFUOVA2b_o
"""

#from google.colab import auth
#auth.authenticate_user()

# https://cloud.google.com/resource-manager/docs/creating-managing-projects
#project_id = 'bigdatainpractice1'
#!gcloud config set project {project_id}

#! gsutil cp gs://grizzy-lab/LoanStats_web.csv ./

#! ls -l

import pandas as pd

raw_pd = pd.read_csv('LoanStats_web.csv')

selected_pd = raw_pd[['int_rate','loan_status','term']]

#type(selected_pd)

#selected_pd.info()

#selected_pd.count()

regex_list = [r'%','months']

selected_pd['int_rate'].replace(regex=regex_list,value='',inplace=True)

selected_pd['term'].replace(regex=regex_list,value='',inplace=True)

selected_pd.fillna('N/A',inplace=True)

#selected_pd.info()

#selected_pd

selected_pd.to_csv('test.json')

#! head -3 test.json

print('Transform completely')
